backend:
  name: github
  repo: max-jellycat/salty-v2

media_folder: static/uploads
public_folder: uploads

collections:
  - name: post
    label: Post
    folder: src/pages/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          name: templateKey,
          label: Template Key,
          widget: hidden,
          default: postTemplate,
        }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Publish Date, widget: datetime }
      - { name: description, label: Description, widget: text }
      - { name: body, label: Body, widget: markdown }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - { name: tags, label: Tags, widget: list }
